package org.example.cookwithmeapi.exceptions.message;

public class AccountExceptionMessage {
    public static String NOT_FOUND_BY_ID = "Account with given id does not exists";
    public static String NOT_FOUND_BY_USERNAME = "Account with given username does not exists";
    public static String NOT_FOUND_BY_EMAIL = "Account with given email does not exists";
    public static String NOT_FOUND_CREATING_RECIPE = "Occurred problem with account";
    public static String USERNAME_ALREADY_TAKEN = "User with given username already exists";
    public static String EMAIL_ALREADY_TAKEN = "User with given email already exists";
}
